### ISSUE TITLE
Technical issues 

### ISSUE THREAD

**Issue by Asethi01** [samantha32123/Project-Repository#7]
1. On the home page it is a bit hard to see the links after you have clicked them once. I think it may be better if you changed their colour and remove the underline. 
2. On the coaching history page, I think it could use a lift-up. The colour scheme does not seem to be easy to read.

**Comment by samantha32123** [comment]
I really appreciate your feedback! I ended up removing the buttons and making the photos clickable instead. I also changed the coaching page based off your suggestions!
